package schema;

import access.DynamoDAO;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
@DynamoDBTable(tableName="Message")
/**
 * Created by kaylafitzsimmons on 1/30/16.
 */

public class MessageItem {


    private String id;
    private String username;
    private String date;
    private String text;


    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() { return id;}
    public void setId(String id) {this.id = id;}

    @DynamoDBAttribute(attributeName="username")
    public String getUsername() {return username; }
    public void setUsername(String username) { this.username = username; }

    @DynamoDBAttribute(attributeName="date")
    public String getDate() {return date; }
    public void setDate(String date) { this.date = date; }

    @DynamoDBAttribute(attributeName="text")
    public String getText(String text) {return text; }
    public void setText(String text) { this.text = text; }

}
